// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalBookAPI.Context;

#nullable disable

namespace MinimalBookAPI.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20230211125204_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalBookAPI.DbModels.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Test first name",
                            Page = 100
                        },
                        new
                        {
                            Id = 2,
                            Name = "Test seconf name",
                            Page = 200
                        },
                        new
                        {
                            Id = 3,
                            Name = "Test fifth name",
                            Page = 500
                        },
                        new
                        {
                            Id = 4,
                            Name = "Test sixth name",
                            Page = 345
                        },
                        new
                        {
                            Id = 5,
                            Name = "Test seventh name",
                            Page = 700
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
